### ISSUE TITLE
place mime types in one file!

### ISSUE THREAD

**Issue by jackttcoms** [OkveeNet/Vfileup#2]
Hello, is it possible to simply place all the mime types in the upload.php instead of having to files and also disable multiple file upload as someone could easily add [] to the end.

Also what is the md5 bit for? `'md5_file' => 'b61e3e0683153ffc198210c6901bd072',`
And for future versions, add an option to restrict image dimentions upload i.e. 200x200px only and also maybe add a zip feature that extracts once uploaded.

Thanks

**Comment by ve3** [comment]
1. For mime types, it is for some app that may not need all of these mime types. The developers can assign mime types them self such as image mime types only. If I place all mime types in upload.php it will be a lot larger file size and the source code will be flood with mime types. I don't think it is good idea to put everything in a file.
2. No, it is not easy just add `[]` and it will work. This class is create for support single file upload and multiple file upload. If you look into the code you will see that it had re-arrange upload array variable and there are functions for multiple files upload. If you think disable multiple files upload is that easy please try it by copy this class and remove anything multiple files upload and add `[]` as you say.
3. `md5_file` is the native PHP function to calculate the hash of uploaded files. See more at [http://php.net/manual/en/function.md5-file.php](http://php.net/manual/en/function.md5-file.php).
4. Restrict image dimension is interesting. I hope to have time to do it.
5. **Zip** feature is too far away from **Upload** class. Sorry, but there already are a lot of good **Zip** class out there. Example: [1](http://php.net/manual/en/class.ziparchive.php) [2](https://github.com/alexcorvi/php-zip) [3](https://github.com/Ne-Lexa/php-zip) [4](https://github.com/alchemy-fr/Zippy) [5 (old package)](https://www.phpclasses.org/package/2495-PHP-Pack-and-unpack-files-packed-in-ZIP-archives.html) & [more...](https://github.com/search?q=php+zip)

**Comment by jackttcoms** [comment]
Ah ok thanks very much! I'm a newbie when it comes to file upload security wise which is why i'm trying to find the perfect class which I think could be yours :)

**Comment by ve3** [comment]
https://github.com/Rundiz/upload/releases/tag/v2.0.3
