### ISSUE TITLE
Mime Types

### ISSUE THREAD

**Issue by heberholanda** [OkveeNet/Vfileup#3]
Hey,
maybe you can add:

`
	'torrent' => array('application/x-bittorrent'),
	'torrent' => array('application/octet-stream'),
`

And as you can see the file can have two mime type, the script only supports the last one that added to the array.

**Comment by ve3** [comment]
In case that you want to add multiple mime type per file extension, please add them in an array.

```
'torrent' => array('application/x-bittorrent', 'application/octet-stream'),
```

**Comment by ve3** [comment]
https://github.com/Rundiz/upload/releases/tag/v2.0.4
