### ISSUE TITLE
Integrate ClamAV

### ISSUE THREAD

**Issue by GoldraK** [OkveeNet/Vfileup#7]
Hello,
First of all, thank you for the package, it works very well.
Looking I see that the part of securityScan you check that there is no php or perl in the file, but I think it would be better to integrate ClamAV that detects many more things.

There is this package in php to be able to use it.

https://github.com/appwrite/php-clamav

Thanks for your job.

**Comment by ve3** [comment]
This is interesting.

**Comment by ve3** [comment]
I was just commit about external security scan here ( https://github.com/Rundiz/upload/commit/e623f36449cb6059764c7a88184deb0218fcad03 ).

The example file is in **tests/via-http/test-clamav.php**

Try to install that class (via composer) on the directory that contain these files **LICENSE, README.md, composer.json**.
Then you should see the new directory **vendor** created here.

I could not make it work on my Linux on Virtual Box. I'm not familiar with Linux command. I can installed ClamAv but when I run, it said:

> Unable to connect to ClamAV server

it would be better if you can test for me on your local PC.

**Comment by ve3** [comment]
Completed, will be publish in 2.0.12 or use `git pull` to always use latest.
